# Generated by Django 3.0.4 on 2020-03-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
