# Generated by Django 3.0.4 on 2020-03-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_store', '0002_orderitem_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
