# Generated by Django 3.0.4 on 2020-03-24 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_store', '0003_auto_20200324_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fecha_completada',
        ),
        migrations.AddField(
            model_name='order',
            name='fecha_orden',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 21, 49, 20, 610061, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
