# Generated by Django 3.0.4 on 2020-03-25 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_store', '0004_auto_20200324_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='item',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookie_store.Item'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
