# Generated by Django 3.0.4 on 2020-03-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_store', '0005_auto_20200325_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='order',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='fecha_orden',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
