# Generated by Django 3.0.4 on 2020-03-30 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_store', '0007_auto_20200326_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cvc',
            field=models.CharField(default='***', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='expire',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
