# Generated by Django 3.0.4 on 2020-04-02 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cookie_store', '0009_auto_20200401_0317'),
    ]

    operations = [
	        migrations.RenameField(
	            model_name='payment',
	            old_name='stripe_charge_id',
        	    new_name='charge_id',
        	),
        	migrations.RemoveField(
			model_name='payment',
            		name='credit_card',
        	),
        	migrations.RemoveField(
			model_name='payment',
            		name='cvc',
        	),
        	migrations.RemoveField(
            		model_name='payment',
            		name='expire',
        	),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cookie_store.Payment')),
                ('credit_card', models.CharField(max_length=20)),
                ('cvc', models.CharField(max_length=4)),
                ('expire', models.DateField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('cookie_store.payment',),
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='payment',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_cookie_store.payment_set+', to='contenttypes.ContentType'),
        ),
    ]
